### PR TITLE
Feature - web page browsing

### PR DESCRIPTION
**Pull request by Loenus**
I think that a web page where to visualize the 'memories' is easier, nicer and more modern to use.
I've added a lot, but the email part hasn't changed, so it should still work as expected @treyg

### CODE REVIEW

**Comment by treyg** [comment]
@Loenus Great idea! I'll get this reviewed and merged, hopefully later today, if not, tomorrow. Thanks for contributing!

**Comment by Loenus** [comment]
Thank you! maybe the only thing missing (I forgot) is to update the images in the readme, maybe showing the webpage? I'm not sure what to show though

**Comment by treyg** [comment]
@Loenus Did you get a chance to test this as a docker image on your NAS? Just wanting to making sure the port selection works as expected in the actual environment. I can test it if not.

**Comment by Loenus** [comment]
@treyg unfortunately today and this weekend I can't, if you can test it that would be great, thanks. Otherwise from Monday I can resume the project and test or improve it if something goes wrong

**Comment by treyg** [comment]
@Loenus no worries! Same here, actually. Have a good weekend!

**Comment by Loenus** [comment]
Hello @treyg! I hope you had a good weekend.
Today I checked it and Indeed I made a mistake, but now it's tested on container manager and it works!

**Comment by treyg** [comment]
@Loenus Nice work! I still haven't had a chance to look at this, but I'm wondering if in the email, we could have a 'view all on web' link that will show you the photos for the time selected (day/week/month). How hard would that be to add to your current branch? I ask because I'm not sure what the webpage currently shows - ie, just photos for that time frame or what. 

If that would be hard for you to add, I could just merge the working PR and add it later.

**Comment by Loenus** [comment]
@treyg I think this should not be difficult since we have NAS_IP, but I have to figure out how to get the local port from the container 🤔

**Comment by Loenus** [comment]
@treyg Figured out it was not possible, so I reintroduced the env PORT which must be the same of the Local Port to make the link in the email work

**Comment by treyg** [comment]
@Loenus That makes sense, but I'm struggling to get the image to run on my NAS. I'm wondering if I'm just missing something. I added the image with the updated code (tag:[0.2.0](https://hub.docker.com/layers/treygordon/synology-photos-memories/0.2.0/images/sha256-b273d8e661d6d98a5a44e8be47220c384f6814091b3abc375242040c9c0473d6?context=repo)) to docker hub if you want to try it on your NAS in container manager to verify it's not just me: 

We're getting close!

**Comment by Loenus** [comment]
@treyg Mh that's strange, when I try to run it (tag `0.2.0`), it gives me ```exec /usr/local/bin/docker-entrypoint.sh: exec format error``` and it stops.
I have previously tested the code with a dockerhub repo of mine and It work.. I don't get where the error is since the codebase should be the same.. Can you try to run my repo, just for testing? [loenus/synology-memories](https://hub.docker.com/r/loenus/synology-memories) (edit: it differs from yours only in that it does not render in the webpage the home.ejs, but the email message)
 
Googling, it turns out it might be releted to the runner's architecture difference. I'm not quite sure tho (because this does not explain to me why my slightly different image work and your not), but It might be worth a try; for example, [someone suggests](https://stackoverflow.com/questions/73398714/docker-fails-when-building-on-m1-macs-exec-usr-local-bin-docker-entrypoint-sh) to specify in the Dockerfile `FROM --platform=linux/amd64 <image>`.. but idk.. if you downloaded the code locally, did you try to run `npm start` (with .env file) and see if it work as expected on your end?

**Comment by treyg** [comment]
@Loenus Looks like it was the issue with the architecture! I would've sworn that wasn't it, since I ran into that issue before, but must be I misremembered. I specified the platform in the dockerfile directly, so we shouldn't run into the same issue in the future. Thanks for the help troubleshooting that!

Other than that, we should be good to go! I made a couple small changes to get the port to work with the IP, but nothing major (it was appending to the `:5001` of quickconnect before), and I also changed the express port from `8080` to `9393`. I did this only because 8080 is popular, and I already have a popular container running on it (that uses it as the default), so I figured others might as well. Let me know if you foresee any issues with `9393` though. 

I have this latest branch running at [0.2.4](https://hub.docker.com/repository/docker/treygordon/synology-photos-memories/general) right now if you want to test it out. I'm going to be out of town for the next 2 days, so I figured we could run that version in the meantime just to make sure there are no bugs before I push it to the latest tag. 

Thanks for your help with this! Great work!

**Comment by Loenus** [comment]
@treyg Thank you for your feedbacks! 
Great it (the platform thing) was a simple fix then!

Only two things

1. " _I made a couple small changes to get the port to work with the IP_ "  I couldn't find the changes you are talking about, but if you are referring to the one call I changed from `5001` to `/photo`, it would works as fine because it's the same (if `photo` is set up like in the README)

2. I wanted to clarify to you one thing, for the future: containers behave like VM, i.e. they are isolated systems. So we can have multiple containers serving services on their own port `8080`. However, to access a container port, it needs to be mapped to the host. For this we do `-p LocalPort:8080` (or the corresponding synology GUI port mapping). So the important thing is that each mapped container has a different `LocalPort`, but the container port can be any! So in our `index.js` we can put `8080` or `9393`, no matter what else you have mapped in your host machine 😉

Other than that, I tried the image (`0.2.4`) and it works for me. BUT I don't use quickconnects and the first time I set it up, I have to trubleshooting the photos not loading. Basically I opened F12 and opened one link of an image in a new tab, then I "accepted the risk" of http; then I reloaded the webpage app and it works as expected. Idk if we want to specify this in the README, although it is not difficult to guess the fix (and it happens only if quickconnects is not set up and only the first time).

Edits: only formatting the text

**Comment by treyg** [comment]
@Loenus Thank you for that clarification! I feel like that's something I should've known, but was just overthinking trying to get it to work 😄. 

As for the port change from `5001` to `/photo`, with the alias setup you added to the readme, how would that work with quickconnect enabled? I just removed the `5001` to the link [here](https://github.com/treyg/synology-photos-memories/blob/66a3ef69f8349d37f6da3ab8907c12b8c3e6c8c3/index.js#L168C49-L168C49), because for me (quickconnect enabled), it would just combine the ports, which obviously doesn't work.

**Pull request merged**
